DP-2800 - Write a Parquet file using schema from data
NorthConcepts/DataPipeline-Examples pull request #120
Opened 2022-12-21 12:10 UTC by gvjoshi25

2022-12-23 18:34 UTC, DeleTaylor requested changes

2022-12-23 18:34 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/examples/parquet/WriteAParquetFileUsingSchemaFromData.java
> +        writer.setSchema(record);
Let's rename this example to `WriteAParquetFileUsingSchemaFromRecord` and create a separate `WriteAParquetFileUsingSchemaFromData` that uses the entire dataset via `DynamicSchemaWriter` behind the scenes.

2022-12-30 14:23 UTC, DeleTaylor approved these changes

2022-12-30 14:23 UTC, merged

2023-01-03 13:08 UTC, gvjoshi25 commented on src/main/java/com/northconcepts/datapipeline/examples/parquet/WriteAParquetFileUsingSchemaFromData.java
> +                .setFieldNamesInFirstRow(true);
Let's use BasicTransformer to convert values to different data type. Currently all values are string data type. Add a comment for the same.