DP-2813 - Add additional stats in example
NorthConcepts/DataPipeline-Examples pull request #134
Opened 2023-01-07 20:37 UTC by chlocarlos

2023-01-07 21:00 UTC, DeleTaylor requested changes

2023-01-07 21:00 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/foundations/examples/pipeline/ShowColumnStatistics.java
> +                System.out.println("    Inferred Numeric Value Count: " + column.getInferredNumericValueCount());
Let's move this outside of the condition so that we can see that it's sometimes zero.

2023-01-07 21:00 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/foundations/examples/pipeline/ShowColumnStatistics.java
> +                System.out.println("    Inferred Temporal Value Count: " + column.getInferredTemporalValueCount());
Let's also move this out of the condition if possible.

2023-01-07 21:00 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/foundations/examples/pipeline/ShowColumnStatistics.java
> +            System.out.println("    Inferred Boolean Value Count: " + column.getInferredBooleanValueCount());
~~What do the leading spaces mean?~~

2023-01-08 03:13 UTC, DeleTaylor requested changes

2023-01-08 03:13 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/foundations/examples/pipeline/ShowColumnStatistics.java
> +            System.out.println("    Inferred Boolean Value Count: " + column.getInferredBooleanValueCount());
Nvm, I understand.

2023-01-08 11:50 UTC, chlocarlos commented on src/main/java/com/northconcepts/datapipeline/foundations/examples/pipeline/ShowColumnStatistics.java
> +                System.out.println("    Inferred Numeric Value Count: " + column.getInferredNumericValueCount());
Done

2023-01-08 11:51 UTC, chlocarlos commented on src/main/java/com/northconcepts/datapipeline/foundations/examples/pipeline/ShowColumnStatistics.java
> +                System.out.println("    Inferred Temporal Value Count: " + column.getInferredTemporalValueCount());
Done

2023-01-08 22:33 UTC, DeleTaylor approved these changes

2023-01-08 22:33 UTC, merged