DP-2879 - Improve database connection usage in parquet example
NorthConcepts/DataPipeline-Examples pull request #138
Opened 2023-01-13 14:03 UTC by gvjoshi25

2023-01-18 02:18 UTC, DeleTaylor requested changes

2023-01-18 02:18 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/examples/parquet/WriteAParquetFileUsingSchemaFromDatabase.java
> +        client.executeFile(new File("example/data/input/user_information.sql"));
Why inline the `executeSqlFile()` method?  (These extra lines here are hiding the real purpose of this example.  I also rather not complicate things by introducing `JdbcConnectionFactory` in the main method.)

2023-01-18 09:18 UTC, gvjoshi25 commented on src/main/java/com/northconcepts/datapipeline/examples/parquet/WriteAParquetFileUsingSchemaFromDatabase.java
> +        client.executeFile(new File("example/data/input/user_information.sql"));
The only reason I moved this code to main is: connection is getting closed after `executeSqlFile()` method as you explained earlier (due to GC).
Another option is to use DB class available in this repository. DB class creates hsql db and connection. I can create another constructor to accept `Connection` only if required.

What do you suggest?

2023-01-19 02:41 UTC, DeleTaylor approved these changes

2023-01-19 02:41 UTC, merged

2023-01-19 02:42 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/examples/parquet/WriteAParquetFileUsingSchemaFromDatabase.java
> +        client.executeFile(new File("example/data/input/user_information.sql"));
@gvjoshi25 yup, using the `DB` class looks better 👍