DP-3636 Add example for GeneratePostgresqlDdl
NorthConcepts/DataPipeline-Examples pull request #188
Opened 2023-11-05 04:33 UTC by sah2020

2023-11-05 20:07 UTC, DeleTaylor requested changes

2023-11-05 20:07 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/examples/cookbook/GeneratePostgreSqlDdlProgrammatically.java
> +        SqlPart createUsersTable = new CreateTable("users")
Let's name tables using the singular -- `user`.  Please update the relevant names that reference the plural as well.

2023-11-05 20:07 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/examples/cookbook/GeneratePostgreSqlDdlProgrammatically.java
> +                .addColumn(new CreateTableColumn("addressId", TableColumnType.INT))
Let's use snake case for database identifiers (and keep them lower case -- even if a particular makes them upper case behinds the scene) -- as is the norm for PostgreSQL and MySQL.

2023-11-05 20:07 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/examples/cookbook/GeneratePostgreSqlDdlProgrammatically.java
> +                .addColumn(new CreateTableColumn("email", TableColumnType.VARCHAR).setUnique(true))
Make sure the set a length for all `varchars`.

2023-11-09 13:56 UTC, sah2020 commented on src/main/java/com/northconcepts/datapipeline/examples/cookbook/GeneratePostgreSqlDdlProgrammatically.java
> +        SqlPart createUsersTable = new CreateTable("users")
it is not possible to create `user` table in PostgreSQL. that's why only this table was named in plural form.

2023-11-09 14:06 UTC, sah2020 commented on src/main/java/com/northconcepts/datapipeline/examples/cookbook/GeneratePostgreSqlDdlProgrammatically.java
> +                .addColumn(new CreateTableColumn("addressId", TableColumnType.INT))
done

2023-11-09 14:06 UTC, akmalxpert commented on src/main/java/com/northconcepts/datapipeline/examples/cookbook/GeneratePostgreSqlDdlProgrammatically.java
> +                .addColumn(new CreateTableColumn("email", TableColumnType.VARCHAR).setUnique(true))
done

2023-11-09 20:53 UTC, DeleTaylor approved these changes

2023-11-09 20:54 UTC, merged