DP-1160 - Create Data Lineage Examples
NorthConcepts/DataPipeline-Examples pull request #28
Opened 2020-11-04 04:29 UTC by gvjoshi25

2020-11-09 13:53 UTC, DeleTaylor requested changes

2020-11-09 13:53 UTC, DeleTaylor commented on src/main/java/com/northconcepts/datapipeline/examples/cookbook/UseDataLineage.java
> +        reader.open();
@gvjoshi25  Please use a custom `DataWriter` (as a static inner class) and `Job.run()` instead of manually opening, closing, and iterating through the reader.

2020-11-09 19:02 UTC, gvjoshi25 commented on src/main/java/com/northconcepts/datapipeline/examples/cookbook/UseDataLineage.java
> +        reader.open();
Done.

2020-11-10 03:55 UTC, DeleTaylor approved these changes

2020-11-10 04:16 UTC, merged